name: "🐞 Bug"
description: Create a new bug report for an unexpected problem or behavior
labels: ["bug"]
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug. Expected behavior and actual behavior. Steps to reproduce.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      description: Backend/Frontend
      options:
        - backend
        - frontend
    validations:
      required: true

  - type: textarea
    id: report_back_to
    attributes:
      label: Report back to
      description: Report back to
      placeholder: Who should be informed about the task when completed?
    validations:
      required: false
  
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: "Enter the deadline (YYYY-MM-DD)"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
