name: "📝 Task"
description: Create a new task for a specific piece of work
labels: []
type: task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the task
      placeholder: What needs to be done?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      description: Backend/Frontend
      options:
        - backend
        - frontend
    validations:
      required: true

  - type: textarea
    id: report_back_to
    attributes:
      label: Report back to
      description: Report back to
      placeholder: Who should be informed about the task when completed?
    validations:
      required: false

  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: "Enter the deadline (YYYY-MM-DD)"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
