name: "🐞 Bug Report"
description: New bug
labels: ["bug"]
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What was supposed to happen?

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened?

  - type: textarea
    id: logs
    attributes:
      label: "Logs & Error Messages"
      description: "Copy and paste any relevant error messages, stack traces, or logs."
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other relevant details that could help debug the issue."

  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      description: Backend/Frontend
      options:
        - backend
        - frontend
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Severity
      options:
        - minor
        - major
    validations:
      required: true

  - type: textarea
    id: report_back_to
    attributes:
      label: Report back to
      description: Report back to
      placeholder: Who should be informed about the task when completed?
    validations:
      required: false
  
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: "Enter the deadline (YYYY-MM-DD)"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
